blank_issues_enabled: false
contact_links:
    - name: Questions and Comments
      url: https://github.com/mlocati/docker-php-extension-installer/discussions
      about: For questions and comments please use Discussions
