#!/bin/sh

. "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/_bootstrap.sh"

if test -z "$(php --ri blackfire | grep 'Blackfire => enabled')"; then
	echo 'Blackfire PHP Probe is disabled' >&2
	rc=1
else
	echo 'Blackfire PHP Probe is enabled'
	rc=0
fi
exit $rc
