#!/bin/sh

set -o errexit
set -o nounset

if test -z "$(php --ri blackfire | grep 'Blackfire => enabled')"; then
	echo 'Blackfire PHP Probe is disabled' >&2
	rc=1
else
	echo 'Blackfire PHP Probe is enabled'
	rc=0
fi
exit $rc
