#!/usr/bin/env php
<?php

require_once __DIR__ . '/_bootstrap.php';

$requiredHandlers = array_map('strtolower', [
    'db4',
]);
$supportedHandlers = array_map('strtolower', dba_handlers(false));
$missingHandlers = array_diff($requiredHandlers, $supportedHandlers);
if ($missingHandlers !== []) {
    sort($missingHandlers);
    fwrite(STDERR, "DBA does NOT support these handlers:\n- " . implode("\n- ", $missingHandlers) . "\n");
    exit(1);
}
echo "DBA supports at least these handlers:\n- ", implode("\n- ", $requiredHandlers), "\n";
