#!/usr/bin/env php
<?php

require_once __DIR__ . '/_bootstrap.php';

list($os, $osVersion) = inspectOS();

$requiredFormats = array_map('strtoupper', [
    'BMP',
    'GIF',
    'JPG',
    'PDF',
    'PNG',
    'SVG',
    'TIFF',
]);
switch ($os) {
    case 'alpine':
        if (version_compare($osVersion, '3.13') >= 0) {
            $requiredFormats[] = 'AVIF';
        }

        break;
    case 'debian':
        if ($osVersion >= 11) { // bullseye
            $requiredFormats[] = 'AVIF';
        }

        break;
    default:
        fwrite(STDERR, "Unsupported OS: {$os}\n");
        exit(1);
}
$requiredFormats = array_map('strtoupper', $requiredFormats);

$supportedFormats = array_map('strtoupper', Imagick::queryFormats());
$missingFormats = array_diff($requiredFormats, $supportedFormats);
if ($missingFormats !== []) {
    sort($missingFormats);
    fwrite(STDERR, "Imagick does NOT support these formats:\n- " . implode("\n- ", $missingFormats) . "\n");
    exit(1);
}
echo "Imagick supports at least these formats:\n- ", implode("\n- ", $requiredFormats), "\n";
