#!/bin/sh

. "$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/_bootstrap.sh"

rc=0
if php --ri igbinary >/dev/null 2>/dev/null; then
	if test -z "$(php --ri yac | grep 'Serializer => .*igbinary')"; then
		echo 'yac has not been compiled with Igbinary support' >&2
		rc=1
	else
		echo 'yac has been compiled with Igbinary support'
	fi
fi
if php --ri json >/dev/null 2>/dev/null; then
	if test -z "$(php --ri yac | grep 'Serializer => .*json')"; then
		echo 'yac has not been compiled with Json support' >&2
		rc=1
	else
		echo 'yac has been compiled with Json support'
	fi
fi
if php --ri msgpack >/dev/null 2>/dev/null; then
	if test -z "$(php --ri yac | grep 'Serializer => .*msgpack')"; then
		echo 'yac has not been compiled with Msgpack support' >&2
		rc=1
	else
		echo 'yac has been compiled with Msgpack support'
	fi
fi
exit $rc
