#!/bin/sh

# Let's set a sane environment
set -o errexit
set -o nounset

apk update
apk del libzip
apk add ebook-tools # <- uses libzip
CI=true ./install-php-extensions zip # <- uses libzip
apk del ebook-tools
php --ri zip
