#!/bin/sh

# Let's set a sane environment
set -o errexit
set -o nounset

if grep -q 'VERSION="8 (jessie)"' /etc/os-release; then
	echo 'Fix Debian Jessie keyring'
	echo 'APT::Get::AllowUnauthenticated "true";' >/etc/apt/apt.conf.d/99-install-php-extensions
fi
