#!/bin/sh

set -o errexit
set -o nounset

. ./scripts/common

# -s        Simplify the code
# -ln posix Language variant: POSIX
# -i 0      Use TAB to indent
# -ci       Switch cases will be indented
# -kp       Keep column alignment paddings
DPEI_PARAMS='-s -ln posix -i 0 -ci -kp'

case "${1:-}" in
	check)
		DPEI_PARAMS="$DPEI_PARAMS -d"
		;;
	fix)
		DPEI_PARAMS="$DPEI_PARAMS -w"
		;;
	*)
		printf 'Syntax: %s <check|fix>\n' "$0" >&2
		exit 1
		;;
esac

DPEI_FILES=install-php-extensions

IFS='
'
for DPEI_FILE in $(find scripts -type f); do
	if test "$(head -n1 $DPEI_FILE)" = '#!/bin/sh'; then
		DPEI_FILES="$DPEI_FILES $DPEI_FILE"
	fi
done

resetIFS

FORCE_COLOR=true shfmt $DPEI_PARAMS -- $DPEI_FILES
