#!/bin/sh

# Let's set a sane environment
set -o errexit
set -o nounset

apt-get update -qq
apt-get upgrade -qqy
apt-get install -qqy libssl-dev

CI=true ./install-php-extensions zip

if test -z "$(dpkg --get-selections | grep -E '^libssl-dev[:\s].*install$')"; then
	echo 'The libssl-dev APT package has not been restored.' >&2
	exit 1
fi

echo 'The libssl-dev APT package has been correctly restored.'
