name: Update README

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - update-readme

jobs:
  update_readme:
    name: Update README
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Update README
        env:
          DEPLOY_KEY: "${{ secrets.DEPLOY_KEY }}"
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: ./scripts/ci-update-readme
